### PR TITLE
Update SCS starter

### LINKED ISSUE #550: Test and Java-CFEnv version
There is a new major version of Java CF Env. Currently at 3.1.5
Spring Boot 3.x application requires java-cfenv 3.1.5 for CloudFoundry.

We need to test the new version with CF.

### PR DESCRIPTION
**Pull request by onobc**
This updates the SCS starter to v4.1.5 and java-cfenv-boot version to v3.2.0 to properly support Boot 3.3.x.

Resolves #550

### CODE REVIEW

**Comment by artembilan** [comment]
I think this might not be related to your change, but the failure is still there:
```
Could not find the selected project in the reactor: spring-cloud-dataflow-apps-plugin/spring-cloud-dataflow-apps-generator-plugin/src/test/resources/unit/http-source-apps
```

**Review by artembilan — APPROVED** [review]
OK with me, but how about that failure on CI?
Thanks

**Comment by onobc** [comment]
> I think this might not be related to your change, but the failure is still there:
> 
> ```
> Could not find the selected project in the reactor: spring-cloud-dataflow-apps-plugin/spring-cloud-dataflow-apps-generator-plugin/src/test/resources/unit/http-source-apps
> ```

Yeh it is unrelated but I will look at it and see if I can fix it now.

**Comment by onobc** [comment]
> > I think this might not be related to your change, but the failure is still there:
> > ```
> > Could not find the selected project in the reactor: spring-cloud-dataflow-apps-plugin/spring-cloud-dataflow-apps-generator-plugin/src/test/resources/unit/http-source-apps
> > ```
> 
> Yeh it is unrelated but I will look at it and see if I can fix it now.

Fixed in https://github.com/spring-cloud/stream-applications/commit/602dee3b94e6021de71f14607cfb80437c201553. Basically the apps plugin module is not one of the Reactor modules and as such should not be included in the magical "what has changed" script that is run as part of the ci-pr.

**Pull request merged**
